services:
  - type: web
    name: telegram-school-sub-bot
    env: python
    repo: https://github.com/czeslaw72/telegram-school-sub-bot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram-bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: TELEGRAM_BOT_TOKEN
        sync: false
