services:
  - type: web
    name: telegram-bot
    env: python
    repo: https://github.com/czeslaw72/telegram-school-sub-bot
    branch: main
    buildCommand: pip install "python-telegram-bot[webhooks]==20.8" pandas python-docx
    startCommand: python telegram-bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 8000
